### ISSUE TITLE
[BUG] Slimes are not spawning in swampland biome

### ISSUE THREAD

**Issue by ShortyDev** [SourceWriters/RealisticWorldGenerator-Api#28]
**Describe the bug**
There are no slimes spawning in the `swampland` biome.
After adding SLIME to the list in the biomes.yml of the world it still doesn't seem to work.

**To Reproduce**
Create a world and find a swampland biome.

**Expected behavior**
Slimes should be spawning in the biome

**Server:**
 - Software: Paper (git-Paper-399)
 - Server Version: 1.17.1
 - Plugin Version: 4.34.13
 - Java Version: 16.0.2+7-67

**Comment by Lauriichan** [comment]
RWG only handles initial Mob spawning, afterwards minecraft itself does the rest.
Slimes are hostile mobs and do not spawn on initial mob spawning, they spawn afterwards naturally therefore this is not a Bug of RWG.
It could be tho that the spawning conditions for slimes aren't met in the Swampland biome, if that is the case then you should check which spawning condition is not fulfilled and adjust your configuration accordingly.
For example too many different blocks so that a slime is unable to spawn

**Comment by Lauriichan** [comment]
And if you add them to the mobs list of the biomes.yml they will, as I said, only spawn once on chunk generation

**Comment by ShortyDev** [comment]
Okay, this doesn't seem to be an issue in RWG then. My problem still persists though, I tried making a large area of grass blocks which are on the same level but the slimes just don't seem to spawn.
I choose a night which has a full moon, too.

According to the [wiki page](https://minecraft.fandom.com/wiki/Slime#Swamps) the light level has to be between 0-7, but on my F3 screen the sky-light-level is 15 and block is 0. Anywhere I go, though when being in water it slightly changes sky and block levels. Is this something that can be changed in RWG or in any other of my server configurations? (Only happening in the world generated by RWG)
![image](https://user-images.githubusercontent.com/68025740/145708813-fd5ad55f-e5bf-4910-bce7-8f2eb29a6bc2.png)

**Comment by ShortyDev** [comment]
I found the issue. The issue was that the height where I tested everything was below 70. Slimes are now spawning and the issue is resolved.

Light-levels seem to be working there too. Weird.

**Comment by Lauriichan** [comment]
Okay that's great ^^
