### ISSUE TITLE
[Feature] Add WorldGuard Support

### ISSUE THREAD

**Issue by TAPGODYT** [SourceWriters/RealisticWorldGenerator-Api#31]
add a region to schematics in order to protect them by default.

**Comment by YellowPhoenix18** [comment]
Please read our plugin-page properly. SmoothTimber already supports WorldGuard

**Comment by TAPGODYT** [comment]
I think my suggestion was not clear enough. So I suggest adding support for the RWG plugin. doing so would allow the server to protect automatically builds that were generated.

**Comment by TAPGODYT** [comment]
example a village spawn well player can't break the village.

**Comment by Lauriichan** [comment]
So first of all sorry that Yellow immediately closed this issue with a reason which makes no sense at all since RWG is not SmoothTimber. It seems like he didn't look at the repository as most of the time only SmoothTimber issues are created.

Then about your suggestion - Please use the correct issue template.
We got templates for a reason and the README states that issues which don't use one of our templates are closed and ignored.
Therefore please create a new issue with the correct template.
